version: "3.7"
services:
  db:
    image: postgres
    container_name: postgresql_metabase
    restart: always
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mynetwork
        
  dataviz:
    image: metabase/metabase
    container_name: metabase
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: db_password
      MB_DB_HOST: db
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - db
    volumes:
      - dataviz_data:/metabase-data
    ports:
      - 3000:3000
    networks:
      - mynetwork

volumes:
  db_data:
  dataviz_data:

networks:
  mynetwork:
    driver: bridge